apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: dev-restricted-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
