apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-db-external-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secretsmanager-cluster-store
    kind: ClusterSecretStore
  target:
    name: k8s-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: prod/db-credentials
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: prod/db-credentials
        property: password
